version: '3'
services:
  # Redis, cache used by Flask
  redis:
    image: "redis:alpine"

  # Flask application
  web:
    build: .
    expose:
      - "8000"
    depends_on:
      - redis
    volumes:
      - uploads:/srv/uploads
      - media:/srv/media
      - sqlite:/srv/sqlite

  # Transcode worker, same image as `web`
  # TODO change to different image??
  transcode:
    build: .
    command: celery worker -l info -A transcoder:celery
    depends_on:
      - redis
    volumes:
      - uploads:/srv/uploads
      - media:/srv/media

  # Frontend
  nginx:
    image: nginx:alpine
    ports: 
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - web
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./static:/srv/static:ro
      - letsencrypt:/etc/letsencrypt:ro
      - media:/srv/media:ro

volumes:
  uploads: # User-uploaded videos
  media: # Transcoded videos
  sqlite: # SQLite DB