version: '3'
services:
  # Redis, cache used by Flask
  redis:
    image: "redis:alpine"

  # Flask application
  web:
    build: .
    expose:
      - "8000"
    depends_on:
      - redis
    volumes:
      - uploads:/srv/uploads

  # Frontend
  nginx:
    image: staticfloat/nginx-certbot
    ports: 
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - web
    environment:
      CERTBOT_EMAIL: ssl@ashtonoh.ms
      ENVSUBST_VARS: FQDN # space-separated
      FQDN: play.ashtonoh.ms
    volumes:
      - ./nginx:/etc/nginx/user.conf.d:ro
      - ./static:/srv/static:ro
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
  uploads: