version: '3'
services:
  # Flask application
  web:
    build: .
    expose:
      - "8000"

  # Redis, cache used by Flask
  redis:
    image: "redis:alpine"

  # Nginx, reverse proxy, provides SSDL  
  nginx:
    build: ./nginx
    ports: 
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  # Certbot, provides a LetsEncrypt certificate
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot